### ISSUE TITLE
All files

### ISSUE THREAD

**Issue by VietTran0302** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst.zh-tw#19]
All files in image folder are untranslated yet

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by olprod** [comment]
The locfile status shown InLocalization, waiting for checkedIn status. [ICMS QUERY](https://wus-000.icms.osi.office.net/vantagepoint/QueryPanel.aspx?Tenant=C%26E&Query=PFZQUT48TEZPPkZhbHNlPC9MRk8%2bPElEPlRydWU8L0lEPjxFTEM%2bRmFsc2U8L0VMQz48QU1QPkZhbHNlPC9BTVA%2bPFNPSFJJUj5GYWxzZTwvU09IUklSPjxTSFJQPkZhbHNlPC9TSFJQPjxTQVRPPkZhbHNlPC9TQVRPPjxTQUxPPlRydWU8L1NBTE8%2bPFFFPj4yPC9RRT48UVQ%2bPjxRUiBJZD0iMSIgQ1BJRD0iMCI%2bQ3VycmVudDtGaWxlcztIb3N0IENvbnRlbnQgU3RvcmU7RXF1YWw7TEFCX1BMLTMwMFQwMDwvUVI%2bPFFSIElkPSIyIiBDUElEPSIwIj5hbmQ7Q3VycmVudDtMb2NGaWxlcztMYW5ndWFnZTtFcXVhbDtDaGluZXNlIChUcmFkaXRpb25hbCk8L1FSPjxRUiBJZD0iMyIgQ1BJRD0iMCI%2bYW5kO0N1cnJlbnQ7RmlsZXM7SG9zdCBGaWxlIFJlZmVyZW5jZTtFcXVhbDsJaHR0cHM6Ly9naXRodWIuY29tL01pY3Jvc29mdExlYXJuaW5nL1BMLTMwMC1NaWNyb3NvZnQtUG93ZXItQkktRGF0YS1BbmFseXN0L2Jsb2IvTWFpbi9JbnN0cnVjdGlvbnMvMDEtcHJlcGFyZS1kYXRhLXdpdGgtcG93ZXItcXVlcnktaW4tcG93ZXItYmktZGVza3RvcC5tZC5tYW5pZmVzdC54bWw8L1FSPjwvUVQ%2bPFJHPjxHQz5OVUxMPC9HQz48L1JHPjwvVlBRPg%3d%3d)

**Comment by chriscarty00** [comment]
Not seeing the art loc in [location](https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst.zh-tw/tree/OLPRODLOC/Instructions/Linked_image_Files)

**Comment by chriscarty00** [comment]
Discussed with the Pm and the images here will not be localised going forward so this is by design
