### ISSUE TITLE
Missing images for all labs in github.io page

### ISSUE THREAD

**Issue by lettucebo** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst.zh-tw#20]
# Module: all modules
#### Step: all steps

Description of issue
Images are missing in every github.io page for ZH-TW labs

![image](https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst.zh-tw/assets/891383/826248c3-a178-484a-a444-6857d50cf448)

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by stonezy123** [comment]
I haven't reproduced the problem.
https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst.zh-tw/blob/OLPRODLOC/Instructions/01-prepare-data-with-power-query-in-power-bi-desktop.md
![image](https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst.zh-tw/assets/49666210/a78cf4f7-cbbc-483c-b526-674c18d30ff6)
